### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by AlexanderBazukevich** [denisnarush/chars-score#1]
```diff
+ 1) [#3] Add choosing value of start-speed.

- 2) Add choosing maximum length for possible chars combination.

+ 3) [#2] Add strict rule to type only by order: first shown letters must be first typed.
+        It gives less chance for random hit.
```

**Comment by denisnarush** [comment]
[#2] Add strict rule to type only by order: first shown letters must be first typed. It gives less chance for random hit.

Done

**Comment by denisnarush** [comment]
[#3] Add choosing value of start-speed.

Done

**Comment by denisnarush** [comment]
> 2) Add choosing maximum length for possible chars combination.

Moving to the _Words_ milestone as:
> [#4] Words Fall Mode
